version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kajaria
      POSTGRES_DB: taskdb
    ports:
      - "1309:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: